table dim_agent

	column agent_id
		dataType: int64
		isKey
		summarizeBy: none
		sourceColumn: agent_id

	column agent_name
		dataType: string
		summarizeBy: none
		sourceColumn: agent_name

	column team
		dataType: string
		summarizeBy: none
		sourceColumn: team

	column hire_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: hire_date

	partition dim_agent = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_agent.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"agent_id", Int64.Type}, {"agent_name", type text}, {"team", type text}, {"speed_factor", type number}, {"hire_date", type date}}),
				    Removed = Table.RemoveColumns(Typed, {"speed_factor"})
				in
				    Removed
