table dim_date
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		summarizeBy: none
		sourceColumn: date

	column date_key
		dataType: int64
		summarizeBy: none
		sourceColumn: date_key

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: int64
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		summarizeBy: none
		sourceColumn: month_name

	column day
		dataType: int64
		summarizeBy: none
		sourceColumn: day

	column day_of_week
		dataType: int64
		summarizeBy: none
		sourceColumn: day_of_week

	column day_name
		dataType: string
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_weekend

	column iso_week
		dataType: int64
		summarizeBy: none
		sourceColumn: iso_week

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"date", type date}, {"date_key", Int64.Type}, {"year", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}, {"iso_week", Int64.Type}})
				in
				    Typed
